//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasteProducts.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LuceneSearchRepository {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LuceneSearchRepository() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WasteProducts.DataAccess.Resources.LuceneSearchRepository", typeof(LuceneSearchRepository).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t clear index..
        /// </summary>
        internal static string ClearIndexError {
            get {
                return ResourceManager.GetString("ClearIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сan&apos;t delete entity with empty id..
        /// </summary>
        internal static string DeleteWithEmptyIdError {
            get {
                return ResourceManager.GetString("DeleteWithEmptyIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t search within empty filelds..
        /// </summary>
        internal static string EmptyFieldsError {
            get {
                return ResourceManager.GetString("EmptyFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сan&apos;t update entity with empty id..
        /// </summary>
        internal static string EmptyIdError {
            get {
                return ResourceManager.GetString("EmptyIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сan&apos;t update entity, provide correct field with id..
        /// </summary>
        internal static string IdFieldNotFound {
            get {
                return ResourceManager.GetString("IdFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t open Lucene index..
        /// </summary>
        internal static string IndexOpenError {
            get {
                return ResourceManager.GetString("IndexOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t find Lucene index storage path settings..
        /// </summary>
        internal static string IndexPathNotFound {
            get {
                return ResourceManager.GetString("IndexPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t optimize index..
        /// </summary>
        internal static string OptimizeIndexError {
            get {
                return ResourceManager.GetString("OptimizeIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t proceed query..
        /// </summary>
        internal static string ProcessQueryError {
            get {
                return ResourceManager.GetString("ProcessQueryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search string can&apos;t be empty or null or consist only from whitespaces.
        /// </summary>
        internal static string QueryStrError {
            get {
                return ResourceManager.GetString("QueryStrError", resourceCulture);
            }
        }
    }
}
